# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, these are Refdir tasks!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  installtools:
    cmds:
      # Install task, go, golangci-lint, cloc externally. E.g via asdf. the needed versions are pinned in .tool-versions file.
      - go install golang.org/x/tools/gopls@v0.20.0
      - go install github.com/oligot/go-mod-upgrade@v0.12.0
      - go install github.com/kisielk/godepgraph@v1.0.0
      - go install github.com/ppipada/refdir@v0.7.0

  cloc:
    cmds:
      - |
        cloc --vcs=git --ignored=ignored.txt \
             --force-lang=Mustache,tmpl --force-lang=INI,env --force-lang=INI,dev --force-lang=INI,prod \
             --exclude_ext=yaml,sum,mod,md5 --not-match-f='LICENSE$|\.gitignore$' \
             .

  godepgraph:
    cmds:
      - godepgraph -s -o github.com/ppipada/refdir,command-line-arguments main.go | dot -Tpng -o godepgraph.png

  lint-godotfix:
    cmds:
      - golangci-lint run --fix --enable-only=godot

  lint-gosort:
    cmds:
      # Use a installed version of this repo.
      - refdir ./...

  lint:
    cmds:
      - golangci-lint run ./... -v

  test:
    cmds:
      - go test ./... -v

  lt:
    cmds:
      - task: lint
      - task: test
