version: "2"

linters:
  default: none
  enable:
    - refdir
  settings:
    custom:
      refdir:
        type: module
        description: "Report potential reference-to-declaration ordering issues"
        original-url: "github.com/ppipada/refdir"
        # All settings are optional.
        # These example settings correspond to the analyzer defaults.
        # Possible values are 'up', 'down', and 'ignore'
        settings:
          directions:
            func: down
            type: up
            recvtype: up
            var: up
            const: up


